In [3]:
import numpy as np
import random

random.seed()
Q = np.zeros((21, 3))
R = np.zeros((21, 3))
R[0][0] = 100
R[0][1] = -100
R[0][2] = -100
R[1][1] = 100
R[1][2] = -100
R[2][2] = 100



def legalRandom(total):
    return np.random.randint(0,3)

def checkGameOver(total):
    if total < 0:
        return True
    else:
        return False

def learn11(Q,r,ep,lrate,disc,games,start):
    for i in range(games):
        #if i%10000==0:
            #print("\nGame ",i," of ",games,"\n")
        total = start-1
        total_run = total
        play = True
        while play:#This plays one game
            if np.random.random()>ep:#greedy step
                choiceCom = np.argmax(Q[total]) #finds the highest valued next state
            else: #epsilon random step
                choiceCom = legalRandom(total) #randomly selects the next legal state
            reward = R[total,choiceCom]
            total_run = total_run - choiceCom - 1
            if checkGameOver(total_run):
        #if the game is over immediatly it means the computer won and learns positivity immediatly
                Q[total,choiceCom] = Q[total,choiceCom]+lrate*(reward+disc*(100)-Q[total,choiceCom])
                play = False

        #before, we had set things up so that it would learn right after it played,
        #but in fact you can only learn something in this game after your opponent plays.
        #Therefore we will include another step to change state again before it learns.
        #We will have it play a random player to start
            else:
                choiceRand = legalRandom(total_run)
                total_run = total_run - choiceRand - 1
                if checkGameOver(total_run):
        #if the opponent ends the game, the computer learns negativity immediatly
                    Q[total,choiceCom] = Q[total,choiceCom]+lrate*(reward+disc*(-100)-Q[total,choiceCom])
                    play = False
                else:
        #otherwise it will learn about its choice based on where it ended up 
                    Q[total,choiceCom] = Q[total,choiceCom]+lrate*(reward+disc*max(Q[total_run])-Q[total,choiceCom])
        
            total = total_run #now we end and repeat till the game is over

learn11(Q,R, ep=.1,lrate=.1,disc=1,games=10000,start=21)
print(Q)

def play11(Q,comFirst=True,start=21):
    total = start -1
    print("Total: ", total+1,"\n")
    if comFirst:
        choice = np.argmax(Q[total])
        total = total - choice -1
        print("Computer chooses: ",choice+1," Total remining: ",total+1,"\n")
    while True:
        while True:
            pchoice = int(input("Player Select 1, 2, or 3: "))
            if((pchoice != 1 and pchoice != 2 and pchoice !=3) or total-pchoice < -1):
                print("Invalid Entry, Please select a legal move")
            else:
                break
        total = total - pchoice
        print("Total remaining: ",total+1,"\n")
        if checkGameOver(total):
            print("Player Wins!!!\n")
            break
        choice = np.argmax(Q[total])
        total = total - choice-1
        print("Computer chooses: ",choice+1," Total remining: ",total+1,"\n")
        if checkGameOver(total):
            print("Computer Wins!!!\n")
            break
            
#play11(Q)

[[ 200.            0.            0.        ]
 [ -99.99858842  200.            0.        ]
 [  30.92857718  -99.99885662  200.        ]
 [  79.33738327  -23.83139108  -94.76652367]
 [ 200.          139.90224634   77.7202909 ]
 [ 133.93766348  200.           52.9477801 ]
 [ 151.95401824  139.0308572   200.        ]
 [  95.96810897  117.41320812  156.71283694]
 [ 200.          146.06609172  134.39349185]
 [ 184.06480182  200.          122.43658531]
 [ 181.28162581  173.98182024  200.        ]
 [ 171.57560124  173.62383849  179.4654397 ]
 [ 200.          185.62365659  193.37509824]
 [ 192.17658144  200.          180.89443087]
 [ 193.29423496  193.09629766  200.        ]
 [ 191.48747408  190.71438396  191.508925  ]
 [ 200.          193.06600037  196.06796163]
 [ 198.77150287  200.          197.86295127]
 [ 196.35589364  189.39201834  190.39568044]
 [   0.            0.            0.        ]
 [ 199.51930356  198.34326932  198.49334179]]
